import type { FrequencyProtocol } from '../../shared/types';

export const FREQUENCY_PROTOCOLS: FrequencyProtocol[] = [
  {
    protocolId: 'ENERGY_RESTORE',
    targetDimension: 'enerji',
    minScore: 5,
    sessions: [
      {
        time: 'morning',
        label: 'Sabah Aktivasyon',
        frequency: 40,
        type: 'binaural_beat',
        carrierHz: 200,
        durationMin: 10,
        waveform: 'sine',
        notes: 'Gözler kapalı, kulaklık zorunlu',
      },
      {
        time: 'midday',
        label: 'Öğle Yenileme',
        frequency: 528,
        type: 'solfeggio',
        durationMin: 7,
        waveform: 'sine',
        notes: 'Hoparlör veya kulaklık',
      },
      {
        time: 'evening',
        label: 'Akşam Toparlanma',
        frequency: 10,
        type: 'isochronic',
        durationMin: 10,
        waveform: 'square',
        notes: 'Sessiz ortam, oturur pozisyon',
      },
    ],
  },
  {
    protocolId: 'NEURO_BALANCE',
    targetDimension: 'norolojik',
    minScore: 5,
    sessions: [
      {
        time: 'morning',
        label: 'Sabah Netlik',
        frequency: 14,
        type: 'isochronic',
        durationMin: 8,
        waveform: 'square',
        notes: 'Gözler açık veya kapalı',
      },
      {
        time: 'afternoon',
        label: 'Stres Boşaltma',
        frequency: 396,
        type: 'solfeggio',
        durationMin: 10,
        waveform: 'sine',
        notes: 'Nefes egzersizi ile birlikte önerilir',
      },
      {
        time: 'night',
        label: 'Gece Sakinleşme',
        frequency: 4,
        type: 'binaural_beat',
        carrierHz: 180,
        durationMin: 15,
        waveform: 'sine',
        notes: 'Yatmadan 30 dk önce, kulaklık zorunlu',
      },
    ],
  },
  {
    protocolId: 'METABOLIC_SUPPORT',
    targetDimension: 'metabolik',
    minScore: 5,
    sessions: [
      {
        time: 'morning',
        label: 'Sabah Metabolizma',
        frequency: 174,
        type: 'solfeggio',
        durationMin: 8,
        waveform: 'sine',
        notes: 'Kahvaltıdan önce, dik oturarak',
      },
      {
        time: 'midday',
        label: 'Öğle Denge',
        frequency: 7.83,
        type: 'schumann',
        durationMin: 10,
        waveform: 'sine',
        notes: 'Mümkünse açık havada',
      },
      {
        time: 'evening',
        label: 'Akşam Detoks',
        frequency: 285,
        type: 'solfeggio',
        durationMin: 8,
        waveform: 'sine',
        notes: 'Akşam yemeğinden 1 saat sonra',
      },
    ],
  },
  {
    protocolId: 'INFLAMMATION_RELIEF',
    targetDimension: 'inflamasyon',
    minScore: 5,
    sessions: [
      {
        time: 'morning',
        label: 'Sabah Hazırlık',
        frequency: 111,
        type: 'monaural',
        durationMin: 7,
        waveform: 'sine',
        notes: 'Hoparlör de kullanılabilir',
      },
      {
        time: 'afternoon',
        label: 'Ağrı Yönetimi',
        frequency: 432,
        type: 'natural_tuning',
        durationMin: 12,
        waveform: 'sine',
        notes: 'Ağrı bölgesine konsantrasyon ile birlikte',
      },
      {
        time: 'night',
        label: 'Gece Onarım',
        frequency: 2,
        type: 'binaural_beat',
        carrierHz: 160,
        durationMin: 15,
        waveform: 'sine',
        notes: 'Uyumadan önce, kulaklık zorunlu',
      },
    ],
  },
  {
    protocolId: 'DIGESTIVE_SUPPORT',
    targetDimension: 'sindirim',
    minScore: 5,
    sessions: [
      {
        time: 'morning',
        label: 'Sabah Aktivasyon',
        frequency: 8,
        type: 'isochronic',
        durationMin: 8,
        waveform: 'square',
        notes: 'Aç karnına, derin nefes ile',
      },
      {
        time: 'pre_meal',
        label: 'Yemek Öncesi',
        frequency: 528,
        type: 'solfeggio',
        durationMin: 5,
        waveform: 'sine',
        notes: 'Ana öğünden 10–15 dk önce',
      },
      {
        time: 'evening',
        label: 'Akşam Rahatlama',
        frequency: 639,
        type: 'solfeggio',
        durationMin: 10,
        waveform: 'sine',
        notes: 'Yemekten 1 saat sonra, yan yatış pozisyonunda',
      },
    ],
  },
  {
    protocolId: 'HORMONAL_BALANCE',
    targetDimension: 'hormonal',
    minScore: 5,
    sessions: [
      {
        time: 'morning',
        label: 'Sabah Ritim',
        frequency: 7.83,
        type: 'schumann',
        durationMin: 10,
        waveform: 'sine',
        notes: 'Güneş ışığında veya sabah yürüyüşü ile kombine',
      },
      {
        time: 'midday',
        label: 'Öğle Denge',
        frequency: 741,
        type: 'solfeggio',
        durationMin: 8,
        waveform: 'sine',
        notes: 'Öğle arası sessiz bir ortamda',
      },
      {
        time: 'night',
        label: 'Gece Reset',
        frequency: 3,
        type: 'binaural_beat',
        carrierHz: 150,
        durationMin: 15,
        waveform: 'sine',
        notes: 'Uyku saatinden 20 dk önce, oda loş olmalı',
      },
    ],
  },
  {
    protocolId: 'IMMUNE_SUPPORT',
    targetDimension: 'immun',
    minScore: 5,
    sessions: [
      {
        time: 'morning',
        label: 'Sabah Güçlendirme',
        frequency: 852,
        type: 'solfeggio',
        durationMin: 10,
        waveform: 'sine',
        notes: 'Günün ilk saatinde, aç karnına',
      },
      {
        time: 'midday',
        label: 'Öğle Koruma',
        frequency: 40,
        type: 'binaural_beat',
        carrierHz: 200,
        durationMin: 8,
        waveform: 'sine',
        notes: 'Kulaklık zorunlu',
      },
      {
        time: 'evening',
        label: 'Akşam Onarım',
        frequency: 432,
        type: 'natural_tuning',
        durationMin: 10,
        waveform: 'sine',
        notes: 'Rahat pozisyon, derin nefes ile',
      },
    ],
  },
  {
    protocolId: 'BIORESONANCE_SENSITIVE',
    targetDimension: 'biyorezonans',
    minScore: 4,
    sessions: [
      {
        time: 'morning',
        label: 'Sabah Zemin',
        frequency: 7.83,
        type: 'schumann',
        durationMin: 12,
        waveform: 'sine',
        notes: 'Mümkünse çıplak ayak, doğal zemin üzerinde',
      },
      {
        time: 'afternoon',
        label: 'Gün İçi Koruma',
        frequency: 963,
        type: 'solfeggio',
        durationMin: 8,
        waveform: 'sine',
        notes: 'Telefon ve ekrandan uzak bir ortamda',
      },
      {
        time: 'night',
        label: 'Gece Arındırma',
        frequency: 0.5,
        type: 'binaural_beat',
        carrierHz: 100,
        durationMin: 20,
        waveform: 'sine',
        notes: 'Tüm elektronikler kapalı, kulaklık, oda karanlık',
      },
    ],
  },
];
